-- VW liste tablosu: /sase/vw tam ekran tablo için
CREATE TABLE IF NOT EXISTS public.sase_vw_formuls (
    id SERIAL PRIMARY KEY,
    ekleyen_kullanici VARCHAR(100),
    baslik VARCHAR(255),
    stok_liste TEXT,
    sase_kod_1 VARCHAR(100),
    sase_kod_2 VARCHAR(100),
    sase_kod_3 VARCHAR(100),
    sase_kod_4 VARCHAR(100),
    sase_kod_5 VARCHAR(100),
    sase_kod_6 VARCHAR(100),
    sase_kod_7 VARCHAR(100),
    sase_kod_8 VARCHAR(100),
    sase_kod_9 VARCHAR(100),
    sase_no VARCHAR(100),
    model VARCHAR(100),
    uretim_tarihi_bas DATE,
    uretim_tarihi_bit DATE,
    model_yili VARCHAR(20),
    satis_tipi VARCHAR(50),
    motor_kodu VARCHAR(100),
    sanzuman_kodu VARCHAR(100),
    aks_tahrigi_tanimi VARCHAR(100),
    donanim VARCHAR(100),
    executed BOOLEAN DEFAULT FALSE,
    execute_date DATE,
    eslenik_sase_adedi INTEGER,
    degerli_aciklama_stok_kods TEXT
);
